name: Build and push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: docker.evidenceprime.com/dexter-dummy-predictor:${{ github.sha }}
          
      - name: Login to Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: docker.evidenceprime.com
          username: ${{ secrets.DOCKER_PUBLIC_LOGIN }}
          password: ${{ secrets.DOCKER_PUBLIC_PASSWORD }}

      - name: Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: docker.evidenceprime.com/dexter-dummy-predictor:${{ github.sha }}